USE covid_economy_impact;
DROP TABLE IF EXISTS housing_date_dim;
CREATE TABLE housing_date_dim
(
    id SERIAL PRIMARY KEY,
    month TINYINT,
    year SMALLINT,
    UNIQUE(month,year)
)ENGINE=InnoDB;

DROP TABLE IF EXISTS city_dim;
CREATE TABLE city_dim
(
     id SERIAL PRIMARY KEY,
     city_name VARCHAR(50) UNIQUE
)ENGINE=InnoDB;

DROP TABLE IF EXISTS metro_dim;
CREATE TABLE metro_dim
(
    id SERIAL PRIMARY KEY,
    metro_city_name VARCHAR(50) UNIQUE

)ENGINE=InnoDB;

DROP TABLE IF EXISTS county_dim;
CREATE TABLE county_dim
(
     id SERIAL PRIMARY KEY,
     county_name VARCHAR(50) UNIQUE
)ENGINE=InnoDB;

CREATE TABLE home_prices_fact
(
    id SERIAL PRIMARY KEY,
    city_id BIGINT UNSIGNED,
    metro_id BIGINT UNSIGNED,
    date_id BIGINT UNSIGNED,
    inventory_date timestamp ,
    state_id BIGINT UNSIGNED,
    county_id BIGINT UNSIGNED,
    mid_tier DECIMAL(13,2) DEFAULT 0.00,
    top_tier DECIMAL(13,2) DEFAULT 0.00,
    bottom_tier DECIMAL(13,2) DEFAULT 0.00,
    single_family DECIMAL(13,2) DEFAULT 0.00,
    condo DECIMAL(13,2) DEFAULT 0.00,
    1bd_room DECIMAL(13,2) DEFAULT 0.00,
    2db_room DECIMAL(13,2) DEFAULT 0.00,
    3bd_room DECIMAL(13,2) DEFAULT 0.00,
    4bd_room DECIMAL(13,2) DEFAULT 0.00,
    5bd_room DECIMAL(13,2) DEFAULT 0.00,
    FOREIGN KEY (date_id) REFERENCES housing_date_dim(id),
    FOREIGN KEY (city_id) REFERENCES city_dim(id),
    FOREIGN KEY (metro_id) REFERENCES metro_dim(id),
    FOREIGN KEY (state_id) REFERENCES state_dim(id),
    FOREIGN KEY (county_id) REFERENCES county_dim(id),
    UNIQUE(city_id, metro_id, date_id, state_id, county_id)
)ENGINE=InnoDB;

CREATE TABLE home_inventory_sales_fact
(
    id SERIAL PRIMARY KEY,
    metro_id BIGINT UNSIGNED,
    date_id BIGINT UNSIGNED,
    inventory_date timestamp NOT NULL,
    state_id BIGINT UNSIGNED,
    for_sale INT,
    median_days_to_sale_pending TINYINT,
    median_list_price DECIMAL(13,2),
    median_sale_price DECIMAL(13,2),
    FOREIGN KEY (date_id) REFERENCES housing_date_dim(id),
    FOREIGN KEY (metro_id) REFERENCES metro_dim(id),
    FOREIGN KEY (state_id) REFERENCES state_dim(id),
    UNIQUE( metro_id, date_id, state_id)
)ENGINE=InnoDB;



/*INSERT into county_dim(name) values
("Los Angeles County"),("Cook County"),("Harris County"),("Maricopa County"),("San Diego County"),("Orange County"),
("Kings County"),("Miami-Dade County"),("Dallas County"),("Queens County"),("Riverside County"),("San Bernardino County"),
("Clark County"),("King County"),("Wayne County"),("Tarrant County"),("Santa Clara County"),("Broward County"),("Bexar County"),("New York County"),
("Philadelphia County"),("Alameda County"),("Middlesex County"),("Suffolk County"),("Sacramento County"),("Bronx County"),("Nassau County"),("Palm Beach County"),
("Cuyahoga County"),("Hillsborough County"),("Allegheny County"),("Oakland County"),("Franklin County"),("Hennepin County"),("Orange County"),
("Fairfax County"),("Contra Costa County"),("Salt Lake County"),("Travis County"),("Saint Louis County"),("Pima County"),("Montgomery County"),("Honolulu County"),
("Westchester County"),("Milwaukee County"),("Fresno County"),("Shelby County"),("Fulton County"),("Mecklenburg County"),("Erie County"),("DuPage County"),
("Fairfield County"),("Pinellas County"),("Bergen County"),("Marion County"),("Wake County"),("Hartford County"),("Duval County"),("Prince Georges County"),
("New Haven County"),
("Macomb County"),
("Kern County"),
("Ventura County"),
("Middlesex County"),
("Gwinnett County"),
 ("San Francisco County"),
("Baltimore County"),
("Hamilton County"),
("El Paso County"),
("Montgomery County")
("Worcester County"),
("Pierce County"),
("Essex County"),
("Collin County"),
("Hidalgo County"),
("Monroe County"),
("Essex County"),
("Jefferson County"),
("Multnomah County"),
("Suffolk County"),
("Oklahoma County"),
("San Mateo County"),
("Snohomish County"),
("Lake County"),
("Dekalb County"),
("Cobb County"),
("San Joaquin County"),
("Will County"),
("Jackson County"),
("Norfolk County"),
("Denton County"),
("Bernalillo County"),
("Jefferson County"),
("Hudson County"),
("Monmouth County"),
("Davidson County"),
("Providence County"),
("Bucks County"),
("El Paso County"),
("Baltimore City"),
("Lee County"),
("Tulsa County"),
("Kent County"),
("Polk County"),
("District of Columbia"),
("Denver County"),
("Fort Bend County"),
("Ocean County"),
("Arapahoe County"),
("Delaware County"),
("Bristol County"),
("Johnson County"),
("Brevard County"),
("Summit County"),
("New Castle County"),
("Anne Arundel County"),
("Union County"),
("Montgomery County"),
("Jefferson County"),
("Washington County"),
("Lancaster County"),
("Douglas County"),
("Utah County"),
("Kane County"),
("Stanislaus County"),
("Camden County"),
("Ramsey County"),
("Passaic County"),
("Chester County"),
("Sedgwick County"),
("Lake County"),
("Plymouth County"),
("Volusia County"),
("Morris County"),
("Guilford County"),
("Dane County"),
("Sonoma County"),
("Spokane County"),
("Richmond County"),
("Onondaga County"),
("Pasco County"),
("Hampden County"),
("Montgomery County"),
("Greenville County"),
("Burlington County"),
("Tulare County"),
("Lucas County"),
("Adams County"),
("East Baton Rouge Parish"),
("Virginia Beach City"),
("York County"),
("Jefferson Parish"),
("Knox County"),
("Polk County"),
("Genesee County"),ß
Clark County
Santa Barbara County
Seminole County
Williamson County
Washoe County
Monterey County
Solano County
Mobile County
Berks County
Cameron County
Prince William County
Hillsborough County
Dakota County
Ada County
Waukesha County
Richland County
Pulaski County
Sarasota County
Clackamas County
Pinal County
Stark County
Orange County
Butler County
Mercer County
Westmoreland County
Saint Charles County
Allen County
Lane County
Forsyth County
Charleston County
Lehigh County
Placer County
Washtenaw County
Orleans Parish
Nueces County
Hamilton County
Madison County
Marion County
Anoka County
Somerset County
Manatee County
Collier County
Luzerne County
Cumberland County
Saint Louis City
Chesterfield County
Marion County
Brazoria County
Loudoun County
Rockland County
Bell County
McHenry County
Henrico County
Davis County
Albany County
Lorain County
Larimer County
Northampton County
Escambia County
Dutchess County
Lake County
Fayette County
Winnebago County
Rockingham County
Boulder County
Anchorage Borough
Galveston County
Gloucester County
Howard County
Douglas County
Lancaster County
Spartanburg County
Cumberland County
Ingham County
Erie County
Lubbock County
Saint Lucie County
Leon County
Greene County
Hamilton County
Atlantic County
New London County
Saint Clair County
San Luis Obispo County
Horry County
Madison County
Osceola County
Dauphin County
Durham County
Saint Joseph County
Chatham County
Ottawa County
Rutherford County
Lexington County
Santa Cruz County
Clayton County
Merced County
Cleveland County
Caddo Parish
Weld County
Marin County
Jefferson County
Thurston County
Kitsap County
Kalamazoo County
Webb County
Brown County
Alachua County
Hinds County
Harford County
Yakima County
Norfolk City
Mahoning County
Buncombe County
Washington County
Cumberland County
McLennan County
Oneida County
Saint Tammany Parish
Frederick County
Weber County
Lake County
Montgomery County
York County
Chesapeake City
Clay County
Lafayette Parish
Benton County
Butte County
Saratoga County
Jefferson County
Niagara County
Barnstable County
Lackawanna County
Cherokee County
Warren County
Linn County
Yavapai County
Trumbull County
Dona Ana County
Washington County
Arlington County
Gaston County
Richmond City
Henry County
Jackson County
Washington County
New Hanover County
Union County
Whatcom County
Champaign County
Yolo County
Broome County
Richmond County
Saint Louis County
Mohave County
Saginaw County
Elkhart County
Sangamon County
Clermont County
Sussex County
York County
Yuma County
Racine County
Shelby County
Brazos County
Tuscaloosa County
Kanawha County
Calcasieu Parish
Clay County
Saint Johns County
Litchfield County
Muscogee County
Canyon County
Anderson County
Harrison County
Peoria County
Hawaii County
Butler County
Williamson County
Ulster County
Baldwin County
El Dorado County
Livingston County
Okaloosa County
Newport News City
Vanderburgh County
Hall County
Cabarrus County
Shawnee County
Berkeley County
Onslow County
Shasta County
Outagamie County
Forsyth County
Benton County
Imperial County
Delaware County
Tippecanoe County
Hernando County
Medina County
Montgomery County
Muskegon County
Beaver County
Monroe County
McLean County
Minnehaha County
Johnston County
Bay County
Pitt County
Carroll County
Winnebago County
Licking County
Kenosha County
Kent County
Middlesex County
Scott County
Porter County
Saint Clair County
Davidson County
Boone County
Kent County
Beaufort County
Greene County
Portage County
DeSoto County
Sumner County
Rock County
Jackson County
Aiken County
Charlotte County
Kenton County
Iredell County
Rensselaer County
Pueblo County
Sarpy County
Hampshire County
Deschutes County
Wyandotte County
Hays County
Cumberland County
Sullivan County
Berrien County
Chittenden County
Bibb County
Maui County
Schenectady County
Catawba County
Centre County
Penobscot County
Ouachita Parish
Kings County
Tolland County
Monroe County
Santa Rosa County
Alamance County
Johnson County
Madera County
Stearns County
Cass County
Franklin County
Ellis County
Sussex County
Schuylkill County
Yellowstone County
Rock Island County
Washington County
Mesa County
Charles County
Merrimack County
Martin County
Fairfield County
Hendricks County
Olmsted County
Santa Fe County
Cambria County
Paulding County
Randolph County
Rankin County
Citrus County
Lee County
Alexandria City
Houston County
Jackson County
Johnson County
Kootenai County
Rowan County
Clark County
Washington County
Indian River County
Monroe County
Hampton City
Ector County
Florence County
Midland County
Fayette County
Dorchester County
Napa County
Calhoun County
Tazewell County
Chautauqua County
Humboldt County
Coconino County
Robeson County
Marathon County
Orange County
Lebanon County
Douglas County
Washington County
Madison County
Rapides Parish
Sandoval County
Guadalupe County
Taylor County
Wichita County
Cochise County
Berkshire County
Black Hawk County
Johnson County
San Juan County
Scott County
Stafford County
Hunterdon County
Livingston Parish
Coweta County
Blair County
Washington County
Sebastian County
Wood County
Wright County
Richland County
Comanche County
Columbia County
Strafford County
Blount County
Washington County
Wayne County
Spotsylvania County
Kennebec County
Oswego County
Gregg County
Tangipahoa Parish
Potter County
Grayson County
Randall County
Morgan County
Pickens County
Boone County
Calhoun County
Windham County
Delaware County
Jasper County
Bossier Parish
Parker County
Skagit County
Clarke County
Linn County
Mercer County
Jefferson County
Lycoming County
Canadian County
Sheboygan County
Kendall County
Harnett County
La Crosse County
Wayne County
Wilson County
La Salle County
Warren County
Kankakee County
Faulkner County
Cache County
Saint Lawrence County
Terrebonne Parish
La Porte County
Allegan County
Douglas County
Macon County
Carroll County
Clark County
Tom Green County
Missoula County
Lowndes County
Warren County
Comal County
Ontario County
Vigo County
Columbiana County
Bay County
Eaton County
Androscoggin County
Douglas County
Sumter County
Navajo County
Brunswick County
Ascension Parish
Saline County
Henderson County
Fayette County
Allen County
Hardin County
DeKalb County
Saint Marys County
Etowah County
Bonneville County
Berkeley County
Craven County
Kaufman County
Whitfield County
Miami County
Cowlitz County
Walworth County
Woodbury County
Fond du Lac County
Tompkins County
Houston County
Ashtabula County
Franklin County
Adams County
Cecil County
Pennington County
Bartow County
Newton County
Lenawee County
Hanover County
Putnam County
Cass County
Yamhill County
Steuben County
Albemarle County
Bradley County
Highlands County
Nevada County
Eau Claire County
Wicomico County
Madison County
Cleveland County
Fairbanks North Star Borough
Cape May County
Roanoke City
Daviess County
Craighead County
Cabell County
Lafourche Parish
Floyd County
Monongalia County
Garland County
Nash County
Flagler County
Portsmouth City
Madison County
Sutter County
Dougherty County
Northumberland County
Montgomery County
Wayne County
Dubuque County
Rockingham County
Sumter County
Geauga County
Pottawattamie County
Marshall County
Lauderdale County
Tuscarawas County
Bowie County
Orangeburg County
Roanoke County
Laramie County
Lawrence County
Carver County
Flathead County
Burke County
Campbell County
Sevier County
Story County
Gallatin County
Platte County
Buchanan County
Grant County
Grafton County
Matanuska Susitna Borough
Indiana County
Chemung County
Crawford County
Dodge County
Calvert County
Sherburne County
Lapeer County
Moore County
Mendocino County
Grand Traverse County
Wood County
Rogers County
Victoria County
Angelina County
Ozaukee County
Hunt County
Muskingum County
Benton County
Rockdale County
Suffolk City
Saint Croix County
Walton County
Jefferson County
Midland County
Saint Clair County
Saint Landry Parish
Caldwell County
Madison County
Lee County
Newport County
Bannock County
Limestone County
Howard County
Josephine County
Talladega County
Clinton County
Orange County
Clearfield County
Vermilion County
Manitowoc County
Cascade County
Burleigh County
Wilson County
Maury County
Cullman County
Cattaraugus County
Lauderdale County
Cayuga County
Glynn County
Scioto County
Elmore County
Raleigh County
Henderson County
Island County
Rockwall County
Frederick County
Lincoln County
Franklin County
Ross County
Somerset County
Sullivan County
Jefferson County
Christian County
Kosciusko County
Payne County
Twin Falls County
Cheshire County
Erie County
White County
Bartholomew County
Lancaster County
Valencia County
Rockingham County
Van Buren County
Leavenworth County
Cole County
Umatilla County
Cape Girardeau County
Liberty County
Lynchburg City
Lewis County
Natrona County
Polk County
Coryell County
Clinton County
Anderson County
Allegany County
Forrest County
Hancock County
Wood County
Floyd County
Putnam County
Bullitt County
Oconee County
Bastrop County
Christian County
Augusta County
Surry County
Madison County
Nassau County
Iberia Parish
Monroe County
Wagoner County
Grays Harbor County
Chelan County
Putnam County
Yuba County
Aroostook County
Apache County
McKinley County
Clallam County
Franklin County
Riley County
De Kalb County
Muskogee County
Shiawassee County
Belmont County
Isabella County
Bulloch County
Grant County
Portage County
Hancock County
Creek County
Jefferson County
Greenwood County
Pottawatomie County
Barrow County
Wilkes County
Harrison County
Armstrong County
Wayne County
Morgan County
Greene County
Walker County
Darlington County
Bedford County
Lonoke County
Walker County
Rutherford County
Jones County
Columbia County
Columbia County
Adams County
Kauai County
Marquette County
Troup County
Walker County
James City County
Grand Forks County
Laurens County
Marion County
Carteret County
Klamath County
Williamson County
Robertson County
Dallas County
Salem County
Butler County
Warren County
Chaves County
Harrison County
McCracken County
York County
Livingston County
Saint Francois County
Carbon County
Fauquier County
Pike County
San Patricio County
Athens County
Lea County
Lake County
Nacogdoches County
Herkimer County
Reno County
Rice County
Spalding County
Blue Earth County
Catoosa County
Ionia County
Otero County
Pittsylvania County
Chatham County
Tehama County
Liberty County
Sampson County
Lewis and Clark County
Montcalm County
Washington County
Columbia County
Pulaski County
Coos County
Bradford County
Hamblen County
Crow Wing County
Lawrence County
Chippewa County
Mercer County
Otsego County
Sauk County
Crawford County
Washington County
Acadia Parish
Pope County
Kershaw County
Ward County
Rutland County
Saint Joseph County
Tipton County
Starr County
Sandusky County
Knox County
Mason County
Franklin County
Stanly County
Garfield County
Jackson County
Oldham County
Jackson County
Georgetown County
Belknap County
Genesee County
Granville County
Lowndes County
Warrick County
Huron County
Washington County
Lenoir County
Barry County
Wise County
Haywood County
Clay County
Laurel County
Walla Walla County
Hall County
Duplin County
Whiteside County
Anderson County
Tooele County
Newton County
Columbus County
Vermilion Parish
Lee County
Oxford County
Carter County
Pike County
Blount County
Otter Tail County
Hawkins County
Columbia County
Seneca County
Windsor County
Boone County
Edgecombe County
Marion County
Garfield County
Franklin County
Cumberland County
Broomfield County
Pearl River County
Tuscola County
Pickaway County
Lamar County
Saline County
Fulton County
Putnam County
Kenai Peninsula Borough
Tuolumne County
Cherokee County
Carson City
San Benito County
Gordon County
Walton County
Venango County
Washington County
Campbell County
Halifax County
Saint Mary Parish
Hardin County
Autauga County
Colbert County
Hancock County
Maverick County
Roane County
Boone County
Henry County
Chisago County
Coles County
Gila County
Jefferson County
Ogle County
Rusk County
Jackson County
Ashland County
Darke County
Russell County
Knox County
Wayne County
Coffee County
Saint Charles Parish
Johnson County
Van Zandt County
Lincoln County
Grady County
Waupaca County
Vernon Parish
Union County
Cass County
Pulaski County
McMinn County
Effingham County
Somerset County
Pender County
Eagle County
Saint Martin Parish
Lyon County
Taney County
Franklin County
Winona County
Worcester County
Jefferson County
La Plata County
Grant County
Hood County
Washington County
Tioga County
Watauga County
Washington County
Crittenden County
Cherokee County
Camden County
Henry County
Chenango County
LeFlore County
Dale County
Montgomery County
Grundy County
Dearborn County
Box Elder County
Coffee County
Bristol County
Lamar County
Bedford County
Jackson County
Gibson County
Dickson County
Kerr County
Boyd County
Henry County
Shelby County
Columbia County
Cortland County
Franklin County
Greene County
Clinton County
Calumet County
Allegany County
Harrisonburg City
Val Verde County
Elko County
Warren County
Jessamine County
Loudon County
Newaygo County
Laurens County
Curry County
Delaware County
Carroll County
Queen Annes County
Macoupin County
Beaufort County
Franklin County
Navarro County
Stephenson County
Oktibbeha County
Carter County
Noble County
Osage County
Santa Cruz County
Stokes County
Lafayette County
Scott County
Washington Parish
Marshall County
Douglas County
Cherokee County
Hoke County
Hopkins County
Fremont County
Lincoln Parish
Chesterfield County
Culpeper County
Hillsdale County
Mifflin County
Richmond County
Kay County
Mississippi County
Gadsden County
Henderson County
Warren County
Goodhue County
Iron County
Lawrence County
Campbell County
Buffalo County
Fayette County
Lincoln County
Medina County
Perry County
Auglaize County
Saint John the Baptist Parish
Huntingdon County
Barron County
Logan County
Pittsburg County
Baldwin County
Bingham County
Calaveras County
Colquitt County
Vance County
Polk County
Branch County
Jefferson County
Phelps County
Tazewell County
Itasca County
Bedford County
Stephens County
McDowell County
Union County
Atascosa County
Siskiyou County
Brown County
Lincoln County
Whitman County
Thomas County
Monroe County
Monroe County
Windham County
Ohio County
Beltrami County
Shelby County
Callaway County
Polk County
Douglas County
Cerro Gordo County
Camden County
Nye County
Hancock County
Dunn County
Dallas County
Sweetwater County
Crawford County
Sullivan County
Chilton County
Highland County
Stevens County
Charlottesville City
Miller County
McKean County
Nelson County
Madison County
Susquehanna County
Waller County
Sanilac County
Danville City
Habersham County
Wilson County
Orleans County
Mecosta County
Butler County
Burnet County
Muscatine County
Fulton County
Wayne County
Gratiot County
Bryan County
Sequoyah County
Jackson County
Holmes County
Coffee County
Preble County
Kandiyohi County
De Kalb County
Pettis County
Barren County
Wyoming County
Greene County
Shelby County
Avoyelles Parish
Clinton County
Shenandoah County
Tioga County
Wood County
Shawano County
Dubois County
Lawrence County
Logan County
Warren County
Marinette County
Union County
Tallapoosa County
Suwannee County
Baxter County
Delaware County
Polk County
Wise County
Ottawa County
Wharton County
Montrose County
Mayes County
Davie County
Webster Parish
Okanogan County
Franklin County
Pierce County
Kittitas County
Bonner County
Jim Wells County
Mercer County
Levy County
Campbell County
Pasquotank County
Marshall County
Pike County
Howell County
Des Moines County
Jackson County
Rio Arriba County
Ravalli County
Fremont County
Tift County
Champaign County
Guernsey County
Okmulgee County
Okeechobee County
Clarion County
Warren County
Knox County
Snyder County
Murray County
Natchitoches Parish
Franklin County
Person County
Floyd County
Essex County
Harrison County
Upshur County
Nez Perce County
Clinton County
Scott County
Mower County
Hendry County
Crawford County
Cheatham County
Defiance County
Cass County
Livingston County
Colleton County
Jefferson County
Waldo County
Greene County
Woodford County
Lawrence County
Chippewa County
Benton County
Knox County
Cooke County
Douglas County
Fayette County
Yadkin County
Dyer County
Escambia County
Montgomery County
Brown County
Amador County
Caldwell County
Webster County
Putnam County
Erath County
Manassas City
Isanti County
Talbot County
Covington County
Clinton County
Oconto County
Williams County
Warren County
Madison County
Newberry County
Pontotoc County
Latah County
Graham County
Alexander County
Calloway County
Marshall County
Lagrange County
Bennington County
Huntington County
Graves County
Fulton County
Delta County
Alcorn County
Clatsop County
Monroe County
Scotts Bluff County
Greenup County
Boone County
Miami County
Coshocton County
Gloucester County
Green County
Jasper County
Addison County
Finney County
Logan County
Matagorda County
Dodge County
McLeod County
Independence County
Houghton County
Steele County
Brown County
Summit County
Ware County
Cowley County
Albany County
Lincoln County
Hale County
Halifax County
Webster County
Scotland County
Perry County
Lee County
Douglas County
Oneida County
Saint Bernard Parish
Lee County
Prince George County
Jasper County
Cocke County
Beauregard Parish
Whitley County
Wapello County
Clark County
Barry County
Laclede County
Morgan County
Greenbrier County
Montgomery County
Carlton County
Sagadahoc County
Isle of Wight County
Seneca County
Bladen County
Hopkins County
Chambers County
Hill County
Weakley County
Howard County
Bureau County
Clarendon County
Lassen County
Madison County
Pulaski County
Lincoln County
De Soto County
Morrow County
Christian County
Panola County
Clark County
Harvey County
McClain County
Putnam County
Lincoln County
Williamsburg County
Adams County
Geary County
Lawrence County
Lincoln County
Effingham County
Chambers County
Silver Bow County
Steuben County
Evangeline Parish
Macon County
Dare County
Fannin County
Ford County
Washington County
Sioux County
Lyon County
Preston County
Gibson County
Orange County
Jasper County
Randolph County
Kendall County
Iberville Parish
Lafayette County
Lincoln County
Marion County
Whitley County
Jackson County
Clinton County
Morrison County
Greene County
Accomack County
Louisa County
McCurtain County
Botetourt County
Chester County
Huron County
Marshall County
Transylvania County
Caroline County
Marion County
Coos County
Monroe County
Taos County
Hot Spring County
Wabash County
Washington County
Sumter County
Oconee County
Miami County
Schoharie County
Wexford County
Mecklenburg County
Nicollet County
Emmet County
Dorchester County
McDonough County
Uintah County
Warren County
Becker County
Jefferson County
Petersburg City
Amherst County
Titus County
Henry County
Leflore County
Adams County
Platte County
Claiborne County
Smyth County
Stone County
Dillon County
Kleberg County
Hardin County
Harris County
Brookings County
Dunklin County
Elk County
Knox County
Bee County
Ottawa County
Rhea County
Obion County
Daviess County
Polk County
Jefferson Davis Parish
Muhlenberg County
Marshall County
Adams County
Malheur County
Juneau Borough
Freeborn County
Caledonia County
Polk County
Delta County
Gallia County
Clare County
Marion County
Wakulla County
Franklin County
Hancock County
Marshall County
Cass County
Logan County
Bryan County
Montgomery County
Wayne County
Garrett County
Carroll County
Stoddard County
Lumpkin County
Pontotoc County
Jefferson County
Vernon County
Pine County
Iroquois County
Neshoba County
Caddo County
Alpena County
Grant County
Giles County
Sunflower County
Copiah County
Pickens County
Randolph County
San Miguel County
Hocking County
Harlan County
Wythe County
Jackson County
McPherson County
Sheridan County
Fayette County
Union County
Orange County
Marlboro County
Russell County
Tate County
Carroll County
Ripley County
Trempealeau County
Marion County
Haralson County
Lake County
Van Wert County
Lincoln County
Perry County
Pike County
Mason County
Bell County
Jones County
Del Norte County
Meade County
Cass County
Adams County
Caroline County
Jennings County
Carroll County
Bradford County
Ellis County
Boyle County
Austin County
Lee County
Gilmer County
Wyoming County
Scott County
Washington County
Saint Francis County
Marion County
Henry County
Mineral County
Park County
Morgan County
Glenn County
Madison County
Palo Pinto County
Yazoo County
Powhatan County
Dinwiddie County
Summit County
Morehouse Parish
Decatur County
Sanpete County
Lauderdale County
Montgomery County
Door County
Henderson County
Hardee County
Carter County
Le Sueur County
Peach County
Barton County
Wells County
Garvin County
Simpson County
Morton County
Custer County
Barbour County
Carroll County
Cherokee County
Mason County
Ashe County
Hardeman County
Orleans County
Codington County
Toombs County
Cibola County
Upson County
White County
Union County
Baker County
Marion County
Lewis County
Elmore County
Edgefield County
Anson County
Clay County
Mingo County
Logan County
Geneva County
Juneau County
De Soto Parish
Grimes County
Oceana County
Montgomery County
Somerset County
Jackson County
Monroe County
Uvalde County
San Jacinto County
Boone County
Nicholas County
Winchester City
Stephens County
Randolph County
Dickinson County
Cheboygan County
Coahoma County
Jefferson County
Ouachita County
Mille Lacs County
Benton County
McNairy County
Hardin County
Chattooga County
Texas County
Franklin County
Cherokee County
Cleburne County
Charlevoix County
Posey County
Brown County
Iosco County
Lyon County
White County
Clarke County
Allen Parish
Union County
Grayson County
Decatur County
Gladwin County
Fluvanna County
Adair County
Lee County
Johnson County
Montezuma County
Audrain County
Tattnall County
Seminole County
Shelby County
Meade County
Abbeville County
Randolph County
Yates County
Prentiss County
Tillamook County
Cass County
Wasco County
Hart County
Washington County
Luna County
Grady County
Plymouth County
Woodford County
Saline County
Washington County
Todd County
Churchill County
Gillespie County
Salem City
Jasper County
Milam County
Miller County
Lincoln County
Manistee County
Crawford County
Hickman County
Hertford County
Grant County
White County
Juniata County
Boone County
Poinsett County
Fayette County
Columbia County
Letcher County
Taylor County
Martin County
Waushara County
Winston County
Lamoille County
Roscommon County
Dawson County
Fredericksburg City
Fayette County
Bremer County
Upshur County
Sabine Parish
Stark County
Scott County
Otsego County
Sumner County
Buchanan County
Lawrence County
Brooke County
Page County
Menominee County
Hampshire County
Fairfield County
Ohio County
Leake County
Panola County
Wyoming County
West Baton Rouge Parish
Meigs County
Staunton City
Houston County
Caswell County
Iowa County
Fannin County
Butts County
King George County
Antrim County
Currituck County
Wasatch County
Osceola County
Routt County
Mitchell County
Ray County
Crisp County
Assumption Parish
Itawamba County
Limestone County
Nodaway County
Saline County
Prince Edward County
Starke County
Johnson County
Teller County
Rowan County
Burke County
Meeker County
Scott County
Aransas County
Franklin County
Elbert County
McDonald County
Monroe County
Plaquemines Parish
Clark County
Jersey County
Seward County
Cassia County
Hockley County
Bibb County
Randolph County
Pointe Coupee Parish
Union Parish
Logan County
Adair County
Jo Daviess County
Grainger County
Payette County
Barnwell County
Wyandot County
Hempstead County
Emanuel County
Hopewell City
George County
Taylor County
Fairfax City
Gray County
Yankton County
Williams County
Mahaska County
Jerome County
Curry County
Shelby County
Logan County
Perry County
Hood River County
Dawson County
Gage County
Grant Parish
Rockbridge County
Henry County
Macon County
Tippah County
Scott County
Yell County
Hutchinson County
Fayette County
Willacy County
Beckham County
Saint James Parish
Northampton County
Franklin County
Overton County
Meriwether County
Morgan County
Grenada County
Moore County
McDuffie County
Dodge County
Tyler County
Phillips County
Clay County
Newton County
Jefferson County
Lincoln County
Goochland County
Leelanau County
Washington County
Ogemaw County
Worth County
Wabasha County
Asotin County
Labette County
Pottawatomie County
Cherokee County
Owen County
Sullivan County
Macon County
Vilas County
Anderson County
Colusa County
Carbon County
Calhoun County
Nobles County
Blaine County
Greene County
Union County
Mercer County
Teton County
Bertie County
Conway County
Jay County
Putnam County
Washington County
Vernon County
Uinta County
Stutsman County
Hampton County
Winneshiek County
Marengo County
Dakota County
Waynesboro City
Crook County
Warren County
Buchanan County
Spencer County
Butler County
Pacific County
Fayette County
Adams County
Colorado County
Fillmore County
Martin County
Fulton County
Concordia Parish
Carroll County
Wayne County
Sevier County
Saunders County
Franklin Parish
Madison County
Wayne County
Clinton County
Richland Parish
Taylor County
Polk County
Texas County
Jones County
Clay County
Kewaunee County
Polk County
Lincoln County
La Paz County
Bandera County
Jackson County
Hubbard County
Klickitat County
East Feliciana Parish
Buena Vista County
McIntosh County
Washington County
Jones County
Kent County
Elbert County
Carroll County
Henry County
De Witt County
Dodge County
Woodward County
Minidoka County
Breckinridge County
Plumas County
Bourbon County
Douglas County
Langlade County
Allen County
Holmes County
Saluda County
Jackson County
Roosevelt County
Orange County
Marion County
Crawford County
Freestone County
Gonzales County
Dickinson County
Pickens County
Montague County
Lincoln County
Lampasas County
Paulding County
Tishomingo County
Covington County
Attala County
Davison County
Deaf Smith County
Perry County
Llano County
Berrien County
Lavaca County
Madison County
Lee County
Winston County
Holmes County
Smith County
Waseca County
Jefferson County
Union County
Hancock County
Green Lake County
Houston County
Arkansas County
Perry County
New Madrid County
Poweshiek County
Otero County
Wright County
Haywood County
Pierce County
Adams County
Dekalb County
Adair County
Duchesne County
Eastland County
Edgar County
Southampton County
Young County
Inyo County
Humphreys County
Pike County
Drew County
Cedar County
Patrick County
New Kent County
Brantley County
Greene County
Banks County
Schuyler County
Lamar County
Unicoi County
McCreary County
Pemiscot County
Montour County
Mariposa County
Johnson County
Appling County
Bosque County
Hart County
Sainte Genevieve County
Clayton County
Franklin County
Richland County
Jackson County
Randolph County
Fentress County
Los Alamos County
Cross County
Pike County
Morgan County
Socorro County
Falls County
Bristol City
Yancey County
Chaffee County
Union County
Avery County
Stone County
Bond County
Tama County
Delaware County
Warren County
Ben Hill County
Cooper County
Washington County
Russell County
Morgan County
Piscataquis County
Hardin County
Gaines County
Benzie County
Mason County
Potter County
Westmoreland County
Brunswick County
Lawrence County
Colonial Heights City
Beadle County
Chickasaw County
Rush County
Parke County
Simpson County
Henry County
Van Buren County
Andrew County
Giles County
Sharp County
Fayette County
Fountain County
Frio County
Cook County
Claiborne Parish
Burleson County
Kalkaska County
Pitkin County
Buckingham County
Chester County
Crawford County
Jasper County
Spencer County
Sevier County
Rockcastle County
Bates County
Hughes County
Wayne County
Gilchrist County
Jefferson County
Atchison County
Scurry County
Garrard County
Taylor County
Jefferson County
Lafayette County
Lawrence County
Polk County
Leon County
Dallas County
Wayne County
Seward County
Piatt County
Gem County
Clay County
Dickinson County
Marion County
Crawford County
Dade County
Robertson County
Lee County
Barbour County
Wetzel County
Pawnee County
Dewitt County
Sawyer County
Dukes County
Humboldt County
Neosho County
Telfair County
Smith County
Benton County
Mercer County
Pike County
Gogebic County
Dixie County
Radford City
Torrance County
Lewis County
Iowa County
Knott County
Clark County
Richland County
Floyd County
Osage County
Rabun County
Jackson Parish
Idaho County
Alleghany County
Brooks County
Kanabec County
Richland County
Vermillion County
Park County
Aitkin County
Ashland County
Baker County
Hill County
Clay County
Redwood County
Greene County
Bamberg County
Casey County
Tipton County
King William County
Page County
Washburn County
Dickenson County
Arenac County
Carbon County
Harrison County
Gulf County
Lawrence County
Nottoway County
Marshall County
San Juan County
Hale County
Otoe County
Renville County
Madison County
Madison County
Hamilton County
Dent County
Park County
Roseau County
West Feliciana Parish
Moniteau County
Mitchell County
Macon County
Kossuth County
Grayson County
Las Animas County
Pecos County
Gooding County
Burnett County
Alamosa County
Walthall County
Massac County
Henry County
Marquette County
Carroll County
Gunnison County
Winn Parish
Floyd County
Brown County
Sibley County
Gasconade County
Nolan County
Choctaw County
Livingston County
Calhoun County
Bourbon County
Jeff Davis County
Mills County
Morgan County
Kingfisher County
Craig County
Nelson County
Bayfield County
Union County
Appomattox County
Cleburne County
Harrison County
Roane County
Dooly County
Oglethorpe County
LaSalle Parish
Pendleton County
Butler County
Missaukee County
Moultrie County
Fulton County
Grand County
Karnes County
Hamilton County
Chowan County
Andrews County
Jefferson County
Rusk County
San Juan County
Macon County
Washington County
Estill County
Mason County
White County
Noble County
Monroe County
Calhoun County
Screven County
Crockett County
Trinity County
Lamar County
Faribault County
Braxton County
Long County
Newton County
Greene County
Union County
O Brien County
Mississippi County
Bienville Parish
Fleming County
Trigg County
McIntosh County
Allamakee County
Manassas Park City
Newton County
Mono County
Saline County
Larue County
Atoka County
Price County
Sequatchie County
Ford County
Jackson County
Crawford County
Williamsburg City
Clarke County
Hardy County
Hughes County
Cedar County
Swain County
Comanche County
Cass County
Clay County
Pennington County
Summers County
Morgan County
Crenshaw County
Jasper County
Greene County
Osage County
Lewis County
Clay County
Wadena County
Converse County
Martinsville City
Clay County
Cannon County
Moffat County
Howard County
Trinity County
Sumter County
Colfax County
Grundy County
Izard County
Douglas County
York County
Madison County
Cass County
Webster County
Kodiak Island Borough
Buffalo County
Callahan County
Wilbarger County
Wayne County
Monroe County
Murray County
Ketchikan Gateway Borough
Perquimans County
Vinton County
Pulaski County
Glacier County
Presque Isle County
Allen County
Stewart County
Koochiching County
Madison County
Goshen County
Fremont County
Wright County
Washington County
Little River County
Pamlico County
Amite County
Bleckley County
Desha County
Pend Oreille County
Caldwell County
Morris County
Lawrence County
Lunenburg County
DeKalb County
Appanoose County
Glades County
Bledsoe County
Red River County
Pike County
Franklin County
Haskell County
Blackford County
Shoshone County
Linn County
Menard County
Amelia County
Butler County
Yalobusha County
Marion County
Marshall County
Crawford County
Powell County
Charlotte County
Johnson County
Prowers County
Union County
Millard County
Jefferson Davis County
Todd County
Grundy County
Chippewa County
Chickasaw County
Barton County
Camp County
Stone County
Northampton County
Bollinger County
Falls Church City
Northumberland County
Perry County
Fulton County
Greensville County
Montgomery County
Madison County
Gates County
Okfuskee County
Charlton County
Shelby County
Edmonson County
Lewis County
Poquoson City
Sussex County
Archuleta County
Cherokee County
Pulaski County
Sierra County
Rio Grande County
Blaine County
Grant County
Heard County
Iron County
Chicot County
Decatur County
Meigs County
Washington County
Custer County
Cottonwood County
Zavala County
Wilcox County
Big Horn County
Jackson County
Washita County
Bath County
Fergus County
Lyon County
Noble County
Franklin County
Lake County
Coosa County
Live Oak County
Owyhee County
Bradley County
Ramsey County
Sanders County
Jefferson County
Lancaster County
Louisa County
Hancock County
Leslie County
Box Butte County
Lowndes County
Pike County
Chattahoochee County
Green County
Scott County
Watonwan County
Lake County
Morrow County
Alleghany County
Latimer County
Essex County
Walsh County
Mackinac County
Bacon County
Barnes County
Skamania County
Red Willow County
Cumberland County
Early County
Evans County
Candler County
Pope County
Boundary County
Monroe County
Middlesex County
Johnston County
Guthrie County
Alcona County
Custer County
Rains County
Bullock County
Oregon County
Lake County
Owen County
Sabine County
Carroll County
Tunica County
Mitchell County
Clay County
Montgomery County
Crawford County
Franklin County
Ward County
Iron County
Switzerland County
Franklin County
Wilkes County
Clay County
Lincoln County
Marion County
Nowata County
Colfax County
Keokuk County
Blanco County
Towns County
Ritchie County
Perry County
Yellow Medicine County
Allendale County
Sac County
Martin County
Emmet County
Clinton County
Jackson County
Grundy County
Webster County
Sublette County
Juab County
Ochiltree County
Lewis County
Washington County
Nantucket County
Teton County
Ralls County
Jones County
Roberts County
Howard County
Caldwell Parish
Marshall County
Butte County
Metcalfe County
Rice County
Carbon County
Lanier County
Cumberland County
Yuma County
White Pine County
Cheyenne County
Brown County
Camden County
Johnson County
Valley County
Humboldt County
Saint Clair County
Swift County
Montmorency County
Richland County
Stevens County
Ozark County
Jasper County
Rock County
Modoc County
Calhoun County
Pratt County
Linn County
Valdez Cordova Borough
Stephens County
Hickory County
Alger County
Pipestone County
Wayne County
Howard County
Wilkinson County
Irwin County
McLean County
Livingston County
Montgomery County
Morgan County
Kiowa County
Marshall County
Hancock County
Caldwell County
Love County
Palo Alto County
Wilson County
Mitchell County
Clay County
Greene County
Crittenden County
Terrell County
Forest County
Deer Lodge County
Carroll County
Clarke County
Benewah County
Wilcox County
Richmond County
Beaverhead County
Monona County
Brewster County
Grand County
Tyler County
Phelps County
Dawes County
Maries County
Cuming County
Charles Mix County
Hamilton County
Montgomery County
Stillwater County
Red River Parish
Clear Creek County
Archer County
Greene County
Jack County
Quay County
Twiggs County
Nevada County
Mathews County
Dawson County
McLean County
Harrison County
Turner County
Taylor County
Lucas County
Coleman County
Sitka Borough
Woods County
Lafayette County
Graham County
Baraga County
Benton County
Cedar County
Monroe County
Trimble County
Clearwater County
Davis County
Marion County
Seminole County
Benton County
Murray County
Pocahontas County
Prairie County
Knox County
Clearwater County
Gilmer County
Cleveland County
Platte County
Oscoda County
Coffey County
Gallatin County
Franklin City
Johnson County
Hancock County
Choctaw County
Clay County
Washakie County
Hamilton County
Warren County
Somervell County
Bracken County
Schoolcraft County
Decatur County
Hamilton County
Shannon County
Greenlee County
Daviess County
Houston County
Mercer County
Butler County
Keith County
Liberty County
Richardson County
Turner County
Jenkins County
Newton County
Lyon County
McCulloch County
Kit Carson County
Conejos County
Ballard County
Custer County
Doddridge County
Searcy County
Monroe County
Traill County
Dallas County
Anderson County
Lincoln County
Tillman County
Monroe County
Doniphan County
Lemhi County
Perry County
Thomas County
Lake County
Lee County
Dade County
Trousdale County
Clay County
Kingman County
Swisher County
Merrick County
Lake County
Chariton County
Grant County
Power County
Randolph County
Forest County
Pendleton County
Madison County
Adair County
Mountrail County
Calhoun County
Pleasants County
Worth County
Van Buren County
Ferry County
Jefferson County
Major County
Union County
Pepin County
Grant County
Fremont County
Harney County
Pembina County
Refugio County
Rappahannock County
Valley County
San Miguel County
Hutchinson County
Henderson County
Lake County
Pierce County
Lac Qui Parle County
Charles City County
Nemaha County
Goliad County
Weston County
Tucker County
Nicholas County
Kane County
Fall River County
Ida County
Crook County
Bon Homme County
Surry County
Wabaunsee County
Galax City
Lexington City
Boise County
Powell County
Wallowa County
Grand Isle County
Caribou County
King and Queen County
Thurston County
Treutlen County
Talbot County
Burt County
Cumberland County
Norman County
Cameron Parish
Bland County
Hancock County
Fulton County
Clinch County
Ontonagon County
Pershing County
Gentry County
Edwards County
Sullivan County
Huerfano County
Reynolds County
Greenwood County
Antelope County
Rio Blanco County
Buena Vista City
Luce County
Wilkin County
Clay County
Bent County
Ellsworth County
Kearney County
Moody County
Jefferson County
Osceola County
Sullivan County
Wayne County
Shelby County
Moore County
McKenzie County
Taylor County
Essex County
Howard County
Greer County
Cotton County
Carson County
Pondera County
Stanton County
Ohio County
Miller County
Audubon County
Saguache County
Ottawa County
Teton County
Stewart County
Grant County
Sherman County
Gray County
Putnam County
Dixon County
Stark County
Bear Lake County
Covington City
Emporia City
Coal County
Morris County
Iron County
Hamlin County
Haskell County
Lincoln County
Fillmore County
Warren County
Crowley County
Chouteau County
Hyde County
Lander County
Wirt County
Day County
Atchison County
Alfalfa County
Beaver County
McCook County
Broadwater County
Van Buren County
Boone County
Lincoln County
Gilpin County
Polk County
McHenry County
Calhoun County
Lincoln County
Toole County
Big Stone County
Tensas Parish
Delta County
Johnson County
Lincoln County
Craig County
Cook County
Kingsbury County
Ringgold County
Carlisle County
Pickett County
Morrill County
Schley County
Putnam County
Mills County
Hickman County
Hamilton County
Washington County
Hot Springs County
Mineral County
Bath County
Kittson County
Grant County
Nuckolls County
Phillips County
Stafford County
Ouray County
Florence County
Tyrrell County
Crane County
Custer County
Oneida County
Custer County
Menominee County
Mineral County
Ellis County
Red Lake County
Columbia County
Edmunds County
Lake of the Woods County
Echols County
Adams County
Storey County
Wahkiakum County
Kearny County
Adams County
Norton City
Smith County
Lewis County
Webster County
Baca County
Donley County
Sweet Grass County
Kinney County
Traverse County
Emmons County
Costilla County
Baker County
Shackelford County
Woodson County
Sierra County
Clay County
Brown County
Granite County
Stanley County
Harmon County
Webster County
Chase County
Pawnee County
Frontier County
Quitman County
Sedgwick County
Highland County
Garfield County
Rich County
Keweenaw County
Judith Basin County
Dolores County
Eureka County
Meagher County
Gilliam County
Cheyenne County
Wheeler County
Kiowa County
Jackson County
Alpine County
Camas County
Hinsdale County
Mineral County
San Juan County*/